image:
  repository: python
  tag: "3.11-slim"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

scripts:
  mountPath: /app

common:
  env: []
  resources: {}

testMsg:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  restartPolicy: Never
  resources: {}

process:
  replicas: 2
  resources: {}

persist:
  replicas: 3
  resources: {}
