apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factor-workloads.fullname" . }}-scripts
  labels:
    {{- include "factor-workloads.labels" . | nindent 4 }}
data:
  test_msg.py: |-
{{ .Files.Get "files/test_msg.py" | indent 4 }}
  process.py: |-
{{ .Files.Get "files/process.py" | indent 4 }}
  persist.py: |-
{{ .Files.Get "files/persist.py" | indent 4 }}
